//© Copyright 2016 Joshua 'JD' Davison - MIT License.
// Generated by CoffeeScript 1.10.0
(function() {
  var TelstraAPI, tAuth, tSMS, tWiFi;

  tAuth = require('./lib/t.auth');

  tSMS = require("./lib/t.sms");

  tWiFi = require("./lib/t.wifi");

  TelstraAPI = (function() {
    function TelstraAPI(CONSUMER_KEY, CONSUMER_SECRET) {
      this.CONSUMER_KEY = process.env.TELSTRA_API_CONSUMER_KEY;
      this.CONSUMER_SECRET = process.env.TELSTRA_API_CONSUMER_SECRET;
      if ((this.CONSUMER_KEY == null) || (this.CONSUMER_SECRET == null)) {
        throw Error("[T.API] Init Error: CONSUMER_KEY or CONSUMER_SECRET missing");
      }
      this.auth = new tAuth(this.CONSUMER_KEY, this.CONSUMER_SECRET);
      this.sms = new tSMS(this.auth);
      this.wifi = new tWiFi(this.auth);
    }

    return TelstraAPI;

  })();

  module.exports = TelstraAPI;

}).call(this);
